# Site settings
title: The Chicago Tech Reader
email: nelsonc1991@siu.edu
description: News, events, and articles about design and devlopment hot off the press from the Windy City.
#http://jailbot.github.io/newspaper-blog
baseurl: "http://jailbot.github.io/newspaper-blog"
url: ""
twitter_username: bigrayarea
github_username:  jailbot

# Build settings
markdown: kramdown
permalink: pretty
timezone: America/Chicago
safe: true
