# Site settings
title: The Chicago Tech Reader
email: nelsonc1991@siu.edu
description: News, events, and articles about design and devlopment hot off the press from the Windy City.
baseurl: ""
url: "http://0.0.0.0:4000"
twitter_username: bigrayarea
github_username:  jailbot

# Build settings
markdown: kramdown
permalink: pretty
timezone: America/Chicago
safe: true
